# ==========================================
# Perfil: LOCAL (IntelliJ / tu PC)
# ==========================================

# Base de datos MySQL local
server.port=8080
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_ENERGI_AI:energiai}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER_MYSQL:root}
spring.datasource.password=${DB_PASSWORD:root}
#spring.datasource.password=${DB_PASSWORD:rootpassword}

# API Data Science local
app.datascience.base-url=${DATASCIENCE_URL:http://localhost:8000}