# ==========================================
# Perfil: DOCKER (contenedores)
# ==========================================

# Base de datos MySQL dentro de Docker
spring.datasource.url=jdbc:mysql://${DB_HOST:db}:${DB_PORT:3306}/${DB_ENERGI_AI:energia_db}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER_MYSQL:root}
spring.datasource.password=${DB_PASSWORD:rootpassword}

# API Data Science dentro de Docker
app.datascience.base-url=${DATASCIENCE_URL:http://data-science:8000}